In [1]:
import numpy as np
import matplotlib
import sklearn
import pandas

In [24]:
# create array, matrix, dataframe
a = np.array([1, 2, 3, 4])

In [25]:
a

array([1, 2, 3, 4])

In [26]:
b = np.array([[1, 2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

In [27]:
# shape
print(a.shape, b.shape)


(4,) (2, 2)


In [28]:
# reshape
c = b.reshape((4, 1))
c

array([[1],
       [2],
       [3],
       [4]])

In [31]:
c.shape

(4, 1)

In [32]:
print(a.shape, b.shape)

(4,) (2, 2)


In [34]:
d = a.reshape((2, 2, 1))
d.shape

(2, 2, 1)

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5])

c = np.concatenate((a, b))
c

array([1, 2, 3, 4, 5])