In [1]:
import numpy as np
import matplotlib
import sklearn
import pandas

In [24]:
# create array, matrix, dataframe
a = np.array([1, 2, 3, 4])

In [25]:
a

array([1, 2, 3, 4])

In [26]:
b = np.array([[1, 2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

In [27]:
# shape
print(a.shape, b.shape)


(4,) (2, 2)


In [28]:
# reshape
c = b.reshape((4, 1))
c

array([[1],
       [2],
       [3],
       [4]])

In [31]:
c.shape

(4, 1)

In [32]:
print(a.shape, b.shape)

(4,) (2, 2)


In [34]:
d = a.reshape((2, 2, 1))
d.shape

(2, 2, 1)

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5])

c = np.concatenate((a, b))
c

array([1, 2, 3, 4, 5])

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a * b
c

array([ 4, 10, 18])

In [19]:
# normalization
mean_c = c.mean()
mean_c

np.float64(10.666666666666666)

In [21]:
std_c = np.std(c)
std_c

np.float64(5.734883511361751)

In [22]:
norm_a = (c - mean_c)/std_c
norm_a

array([-1.16247639, -0.11624764,  1.27872403])

In [23]:
np.mean(norm_a)

np.float64(1.4802973661668753e-16)

In [24]:
np.std(norm_a)

np.float64(1.0)

In [25]:
#Project: Data Standardization
import numpy as np

# --- Step 1: Define Raw Data ---
# Let's imagine we want to predict house prices using two features:
# 1. Square footage (large values)
# 2. Number of bedrooms (small values)
# This difference in scale can negatively impact a model's performance.

# Define the raw data array
# Column 0: Square footage
# Column 1: Number of bedrooms
raw_data = np.array([
    [1500, 2],
    [2000, 3],
    [3500, 4],
    [1000, 2],
    [2500, 3]
])
print("Raw Data:\n", raw_data)

# --- Step 2: Standardize the Data ---
# Standardization transforms the data to have a mean of 0 and a standard deviation of 1.
# This ensures all features are on a similar scale.

# Calculate the mean and standard deviation for each column (feature)
mean_values = np.mean(raw_data, axis=0)
std_values = np.std(raw_data, axis=0)

print("\nMean of each column:", mean_values)
print("Standard Deviation of each column:", std_values)

# Apply the standardization formula: (value - mean) / standard_deviation
standardized_data = (raw_data - mean_values) / std_values

print("\nStandardized Data:\n", standardized_data)

# --- Step 3: Verify the Results ---
# We can confirm the standardization by checking the mean and standard deviation
# of the new, transformed data.

# Calculate the mean of the standardized data
mean_standardized = np.mean(standardized_data, axis=0)

# Calculate the standard deviation of the standardized data
std_standardized = np.std(standardized_data, axis=0)

print("\nMean of standardized data:", mean_standardized)
print("Standard Deviation of standardized data:", std_standardized)

# The output shows means very close to zero and standard deviations of exactly 1.
# This confirms that the standardization was successful.
# The `standardized_data` is now ready to be used to train a machine learning mod




Raw Data:
 [[1500    2]
 [2000    3]
 [3500    4]
 [1000    2]
 [2500    3]]

Mean of each column: [2100.     2.8]
Standard Deviation of each column: [8.60232527e+02 7.48331477e-01]

Standardized Data:
 [[-0.69748583 -1.06904497]
 [-0.11624764  0.26726124]
 [ 1.62746694  1.60356745]
 [-1.27872403 -1.06904497]
 [ 0.46499055  0.26726124]]

Mean of standardized data: [1.11022302e-17 2.22044605e-16]
Standard Deviation of standardized data: [1. 1.]
