In [3]:
from sklearn.datasets import load_breast_cancer
bc =load_breast_cancer()

In [4]:
print (bc.DESCR)



.. _breast_cancer_dataset:

Breast cancer Wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - 

# Dataset Info

In [5]:
bc.target[500]
# Dataset Information

np.int64(1)

In [6]:
bc.target.shape
# Features Information

(569,)

In [7]:
bc.data[500]
# we see 500th sample's features values

array([1.504e+01, 1.674e+01, 9.873e+01, 6.894e+02, 9.883e-02, 1.364e-01,
       7.721e-02, 6.142e-02, 1.668e-01, 6.869e-02, 3.720e-01, 8.423e-01,
       2.304e+00, 3.484e+01, 4.123e-03, 1.819e-02, 1.996e-02, 1.004e-02,
       1.055e-02, 3.237e-03, 1.676e+01, 2.043e+01, 1.097e+02, 8.569e+02,
       1.135e-01, 2.176e-01, 1.856e-01, 1.018e-01, 2.177e-01, 8.549e-02])

In [8]:
bc.data.shape
# we have 569 samples and each sample has 30 features

(569, 30)

# Preprocessing

In [9]:
# in this step we will do preprocessing its means we will spalit our data into train and test sets and normalize it 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(bc.data, bc.target, test_size=0.2, random_state=42)

In [10]:
print(f"Feature=> train: {X_train.shape} - test: {X_test.shape}")
print(f"Label=> train: {y_train.shape} - test: {y_test.shape}")

# it means we have 455 samples for training and 114 samples for testing and each sample has 30 features 

Feature=> train: (455, 30) - test: (114, 30)
Label=> train: (455,) - test: (114,)


In [11]:
X_train[0]

array([9.029e+00, 1.733e+01, 5.879e+01, 2.505e+02, 1.066e-01, 1.413e-01,
       3.130e-01, 4.375e-02, 2.111e-01, 8.046e-02, 3.274e-01, 1.194e+00,
       1.885e+00, 1.767e+01, 9.549e-03, 8.606e-02, 3.038e-01, 3.322e-02,
       4.197e-02, 9.559e-03, 1.031e+01, 2.265e+01, 6.550e+01, 3.247e+02,
       1.482e-01, 4.365e-01, 1.252e+00, 1.750e-01, 4.228e-01, 1.175e-01])

In [12]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0, 1))

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
X_train[0]

array([0.06552721, 0.25769361, 0.07732252, 0.03436883, 0.48722578,
       0.41750565, 0.73336457, 0.21744533, 0.50400427, 0.64237574,
       0.07818215, 0.18427334, 0.05314988, 0.02029892, 0.26637658,
       0.62943491, 0.76717172, 0.62928585, 0.63623129, 0.29933115,
       0.05964476, 0.28331557, 0.05597072, 0.02508436, 0.523195  ,
       0.44938009, 1.        , 0.60137457, 0.52493594, 0.52950153])

# Classification

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

def claculate_metrics(y_train, y_test, y_pred_train, y_pred_test):
    acc_train = accuracy_score(y_true=y_train, y_pred=y_pred_train)
    acc_test = accuracy_score(y_true=y_test, y_pred=y_pred_test)
    
    p = precision_score(y_true=y_test, y_pred=y_pred_test)
    r = recall_score(y_true=y_test, y_pred=y_pred_test)
    
    print(f"acc train: {acc_train} - acc test: {acc_test} - precision: {p} - recall: {r}")
    
    return acc_train, acc_test, p, r

# we wrtie this function to calculate the metrics of our model and dont need repeat next time.
# it will return accuracy for train and test sets as well as precision and recall for test sets
# we will use this function after training each model


## 1. Naive bayes

In [21]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [24]:
y_pred_train = gnb.predict(X_train)
y_test_pred = gnb.predict(X_test)

acc_train_gnb, acc_test_gnb, p_gnb, r_gnb = claculate_metrics(y_train, y_test, y_pred_train, y_test_pred)

# Now we have trained Gaussian Naive Bayes model and calculated its metrics

acc train: 0.9362637362637363 - acc test: 0.9649122807017544 - precision: 0.958904109589041 - recall: 0.9859154929577465


## 2.KNN

In [26]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5, algorithm='kd_tree', leaf_size=25)
knn.fit(X_train, y_train)


KNeighborsClassifier(algorithm='kd_tree', leaf_size=25)

In [28]:
y_pred_train = knn.predict(X_train)
y_test_pred = knn.predict(X_test)

acc_train_knn, acc_test_knn, p_knn, r_knn = claculate_metrics(y_train, y_test, y_pred_train, y_test_pred)

# Now we have trained KNN model and calculated its metrics 

acc train: 0.9758241758241758 - acc test: 0.9649122807017544 - precision: 0.971830985915493 - recall: 0.971830985915493


## 3.Descision tree

In [70]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(max_depth=100, min_samples_split=3, criterion='entropy')
dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=100, min_samples_split=3)

In [71]:
y_pred_train = dt.predict(X_train)
y_test_pred = dt.predict(X_test)

acc_train_dt, acc_test_dt, p_dt, r_dt = claculate_metrics(y_train, y_test, y_pred_train, y_test_pred)

acc train: 0.9978021978021978 - acc test: 0.956140350877193 - precision: 0.9459459459459459 - recall: 0.9859154929577465


## 4.Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=500, max_depth=70, min_samples_split=7, criterion='entropy')
